
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.vo.Requerimiento1;
import model.vo.Requerimiento2;
import model.vo.Requerimiento3;
import static view.VistaRequerimientosReto4.controlador;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tcald
 */
public class Gui_Reto5 extends javax.swing.JFrame {

    /**
     * Creates new form Gui_Reto5
     */
    public Gui_Reto5() {
        initComponents();
        setVisible(true);
        setTitle("EDILBERTO CALDERÓN T");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelContainer = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        projectPanel = new javax.swing.JPanel();
        projectPanelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProjects = new javax.swing.JTable();
        bankPanel = new javax.swing.JPanel();
        projectPanelTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBanks = new javax.swing.JTable();
        materialPanel = new javax.swing.JPanel();
        projectPanelTitle2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMaterials = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Proyectos");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bancos");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Materiales");

        jButton1.setText("Consultar");
        jButton1.setActionCommand("btnProyectos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Reto 5- Misión-tic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jButton2)))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContainer.setBackground(new java.awt.Color(255, 255, 255));
        panelContainer.setLayout(new java.awt.CardLayout());

        defaultPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        panelContainer.add(defaultPanel, "card2");

        projectPanel.setBackground(new java.awt.Color(255, 255, 255));

        projectPanelTitle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        projectPanelTitle.setForeground(new java.awt.Color(0, 0, 0));
        projectPanelTitle.setText("Proyectos con mayor inversión");

        jScrollPane1.setViewportView(tableProjects);

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(projectPanelTitle))
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(projectPanelTitle)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        panelContainer.add(projectPanel, "card2");

        bankPanel.setBackground(new java.awt.Color(255, 255, 255));

        projectPanelTitle1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        projectPanelTitle1.setForeground(new java.awt.Color(0, 0, 0));
        projectPanelTitle1.setText("Áreas de construcción de proyectos y banco que la respalda");

        jScrollPane2.setViewportView(tableBanks);

        javax.swing.GroupLayout bankPanelLayout = new javax.swing.GroupLayout(bankPanel);
        bankPanel.setLayout(bankPanelLayout);
        bankPanelLayout.setHorizontalGroup(
            bankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankPanelLayout.createSequentialGroup()
                .addGroup(bankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bankPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(projectPanelTitle1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        bankPanelLayout.setVerticalGroup(
            bankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(projectPanelTitle1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        panelContainer.add(bankPanel, "card2");

        materialPanel.setBackground(new java.awt.Color(255, 255, 255));

        projectPanelTitle2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        projectPanelTitle2.setForeground(new java.awt.Color(0, 0, 0));
        projectPanelTitle2.setText("Materiales importados menos comprados");

        jScrollPane3.setViewportView(tableMaterials);

        javax.swing.GroupLayout materialPanelLayout = new javax.swing.GroupLayout(materialPanel);
        materialPanel.setLayout(materialPanelLayout);
        materialPanelLayout.setHorizontalGroup(
            materialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialPanelLayout.createSequentialGroup()
                .addGroup(materialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(materialPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(projectPanelTitle2)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        materialPanelLayout.setVerticalGroup(
            materialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(projectPanelTitle2)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        panelContainer.add(materialPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelContainer.removeAll();
        panelContainer.add(projectPanel);
        panelContainer.repaint();
        panelContainer.revalidate();
        ArrayList<Requerimiento1> rankingProyectosCompras = null;
        try {
            rankingProyectosCompras = controlador.consultarProyectosCompras10();
        } catch (SQLException ex) {
            Logger.getLogger(Gui_Reto5.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelo = new DefaultTableModel();
        tableProjects.setModel(modelo);
        modelo.addColumn("Id Proyecto");
        modelo.addColumn("Clasificación");
        modelo.addColumn("Gasto Compras");
        modelo.addColumn("Serial");
        if (rankingProyectosCompras != null) {
            for (int i = 0; i <= rankingProyectosCompras.size(); i++) {
                Object[] fila = new Object[4];
                fila[0] = rankingProyectosCompras.get(i).getIdProyecto();
                fila[1]= rankingProyectosCompras.get(i).getClasificacion();
                fila[2]= rankingProyectosCompras.get(i).getGastoCompras();
                fila[3]= rankingProyectosCompras.get(i).getSerial();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         panelContainer.removeAll();
        panelContainer.add(bankPanel);
        panelContainer.repaint();
        panelContainer.revalidate();
        ArrayList<Requerimiento2> rankingBancosArea = null;
        try {
             rankingBancosArea = controlador.consultarBancosRankeadosAreaPromedio();
        } catch (SQLException ex) {
            Logger.getLogger(Gui_Reto5.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelo = new DefaultTableModel();
        tableBanks.setModel(modelo);
        modelo.addColumn("Banco Vinculado");
        modelo.addColumn("Área Promedio");
       
        if (rankingBancosArea != null) {
            for (int i = 0; i <= rankingBancosArea.size(); i++) {
                Object[] fila = new Object[2];
                fila[0] = rankingBancosArea.get(i).getBancoVinculado();
                fila[1]= rankingBancosArea.get(i).getAreaPromedio();
                
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelContainer.removeAll();
        panelContainer.add(materialPanel);
        panelContainer.repaint();
        panelContainer.revalidate();
       ArrayList<Requerimiento3> rankingMaterialesImportados= null;
        try {
            rankingMaterialesImportados = controlador.consultarMaterialesRankeadosCompras();
        } catch (SQLException ex) {
            Logger.getLogger(Gui_Reto5.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelo = new DefaultTableModel();
        tableMaterials.setModel(modelo);
        modelo.addColumn("Nombre Material");
        modelo.addColumn("Importado");
        modelo.addColumn("No. Compras");
       
        if (rankingMaterialesImportados != null) {
            for (int i = 0; i <= rankingMaterialesImportados.size(); i++) {
                Object[] fila = new Object[3];
                fila[0] = rankingMaterialesImportados.get(i).getNombreMaterial();
                fila[1]= rankingMaterialesImportados.get(i).getImportado();
                fila[2]= rankingMaterialesImportados.get(i).getNoCompras();
                
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Reto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Reto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bankPanel;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel materialPanel;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JLabel projectPanelTitle;
    private javax.swing.JLabel projectPanelTitle1;
    private javax.swing.JLabel projectPanelTitle2;
    private javax.swing.JTable tableBanks;
    private javax.swing.JTable tableMaterials;
    private javax.swing.JTable tableProjects;
    // End of variables declaration//GEN-END:variables
}
